### ISSUE TITLE
Uptimerobot Channel Description

### ISSUE THREAD

**Issue by caneabi** [irgendwr/sinusbot-scripts#5]
Hey, wollte dich fragen ob es möglich wäre mehrere Monitore in einer Channelbeschreibung anzugeben, also sprich:

Musicbots: Online
Website: Online
Ranksystem: Down

Bis jetzt ist es leider nur möglich einen Monitor pro Channel einzustellen

**Comment by irgendwr** [comment]
Da ich das sowohl dieses script, als auch TeamSpeak nicht mehr aktiv nutze, ist es unwahrscheinlich, dass ich dieses feature in nächster Zeit einbaue.
Falls jemand lust hat: pull-requests sind willkommen :)

**Comment by irgendwr** [comment]
not working on this anymore
